theme = "selenized_dark"

[editor]
completion-timeout = 25

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.g]
q = ":reflow"
# Replace smart quotes with normal
"\"" = ":pipe sd \"’\" \"'\" | sd '(“|”)' '\"'"
# Replace with em dash and en dash
"-" = ":pipe sd -- '---' '—' | sd -- '--' '–'"

[keys.normal.space]
x = ":toggle whitespace.render all none"
