theme = "selenized_dark"

[editor]
completion-timeout = 25
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal.g]
q = ":reflow"
# Replace smart quotes with normal
"\"" = ":pipe sd \"’\" \"'\" | sd '(“|”)' '\"'"
# Replace with em dash and en dash
"-" = ":pipe sd -- '---' '—' | sd -- '--' '–'"
# Git blame in the editor (requires nightly, atm)
# Ref: https://github.com/helix-editor/helix/discussions/6421#discussioncomment-12486943
B = ":sh git log -n 5 --no-patch --pretty=format:'%%h -%%d %%s (%%cr) <%%aN>' -L%{cursor_line},+1:%{buffer_name}"

[keys.normal.space]
x = ":toggle whitespace.render all none"
