[language-server.rust-analyzer]
config = { procMacro = { ignored = { leptos_macro = [
	# Optional:
	# "component",
	"server"
] } } }

[language-server.tinymist]
command = "tinymist"

[language-server.typos]
command = "typos-lsp"
config.diagnosticSeverity = "Info"

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "email"
scope = "text.email"
roots = []
file-types = ["eml", "email"]
rulers = [72]
language-servers = [ "ltex-ls", "typos" ]
text-width = 72

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "latex"
language-servers = [ "texlab", "ltex-ls", "typos" ]

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls", "typos" ]
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "scss"
indent = { tab-width = 2, unit = " " }

[[language]]
name = "just"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "rust"

[[language]]
name = "typst"
language-servers = ["tinymist", "typos"]

[[language]]
name = "python"
rulers = [100]
text-width = 100
language-servers = ["ruff", "typos"]
auto-format = true
