on: 
  schedule:
    - cron: "0 0 1 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
name: Prune Old Images
env:
  # Exclude LFS files
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  prune:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: prune omakase-toolbox
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'omakase-toolbox'
          package-type: 'container'
          min-versions-to-keep: 15
